#!/bin/bash

# Print Layout Composer
# Creates 8.5x11 printable pages with multiple game images
# Optimizes space usage by fitting as many images as possible per page
#
# USAGE:
#   ./print_composer.sh [input_directory]
#
#   If no directory is specified, uses the current directory.
#
# REQUIREMENTS:
#   - ImageMagick 7.x (magick command)
#   - Input images should be 638x1012 pixels (generated by imagemagick_composer.sh)
#   - Images must be PNG format
#
# OUTPUT:
#   - Creates a 'print_output' directory containing numbered page files
#   - Pages are 8.5x11 inches at 300 DPI (2550x3300 pixels)
#   - Each page fits 3 images (3 columns × 1 row)
#   - Output files: page_001.png, page_002.png, etc.
#
# EXAMPLE:
#   ./print_composer.sh gba/output
#   ./print_composer.sh

# Trap SIGINT (Ctrl+C) for clean exit
trap 'echo ""; echo "Interrupted by user. Exiting..."; exit 130' INT

# Configuration
INPUT_DIR="${1:-.}"
OUTPUT_DIR="print_output"
DPI=300

# Page dimensions at 300 DPI (8.5 x 11 inches)
PAGE_WIDTH=2550
PAGE_HEIGHT=3300

# Image dimensions (from template)
IMAGE_WIDTH=638
IMAGE_HEIGHT=1012

# Margins (0.25 inch on all sides)
MARGIN=75
USABLE_WIDTH=$((PAGE_WIDTH - 2 * MARGIN))
USABLE_HEIGHT=$((PAGE_HEIGHT - 2 * MARGIN))

# Calculate layout
IMAGES_PER_ROW=$((USABLE_WIDTH / IMAGE_WIDTH))
IMAGES_PER_COL=$((USABLE_HEIGHT / IMAGE_HEIGHT))
IMAGES_PER_PAGE=$((IMAGES_PER_ROW * IMAGES_PER_COL))

# Calculate spacing to center images
HORIZONTAL_SPACING=$(((USABLE_WIDTH - (IMAGES_PER_ROW * IMAGE_WIDTH)) / (IMAGES_PER_ROW + 1)))
VERTICAL_SPACING=$(((USABLE_HEIGHT - (IMAGES_PER_COL * IMAGE_HEIGHT)) / (IMAGES_PER_COL + 1)))

echo "Print Layout Composer"
echo "====================="
echo "Input directory: $INPUT_DIR"
echo "Output directory: $OUTPUT_DIR"
echo "Page size: 8.5x11 inches at ${DPI} DPI (${PAGE_WIDTH}x${PAGE_HEIGHT} pixels)"
echo "Image size: ${IMAGE_WIDTH}x${IMAGE_HEIGHT} pixels"
echo "Images per page: ${IMAGES_PER_PAGE} (${IMAGES_PER_ROW} columns × ${IMAGES_PER_COL} rows)"
echo ""

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Find all PNG images in input directory
mapfile -d '' images < <(find "$INPUT_DIR" -maxdepth 1 -type f -iname "*.png" -print0 | sort -z)
total_images=${#images[@]}

if [ "$total_images" -eq 0 ]; then
    echo "Error: No PNG images found in '$INPUT_DIR'"
    exit 1
fi

echo "Found $total_images images"
total_pages=$(((total_images + IMAGES_PER_PAGE - 1) / IMAGES_PER_PAGE))
echo "Will create $total_pages page(s)"
echo ""

# Process images page by page
page_num=1
image_index=0

while [ "$image_index" -lt "$total_images" ]; do
    echo "Creating page $page_num..."
    
    page_file="${OUTPUT_DIR}/page_$(printf "%03d" $page_num).png"
    
    # Build composite command with all images for this page
    composite_cmd="magick -size ${PAGE_WIDTH}x${PAGE_HEIGHT} xc:white -colorspace sRGB"
    
    images_on_page=0
    
    for row in $(seq 0 $((IMAGES_PER_COL - 1))); do
        for col in $(seq 0 $((IMAGES_PER_ROW - 1))); do
            if [ "$image_index" -ge "$total_images" ]; then
                break 2
            fi
            
            current_image="${images[$image_index]}"
            
            # Calculate position
            x=$((MARGIN + HORIZONTAL_SPACING + col * (IMAGE_WIDTH + HORIZONTAL_SPACING)))
            y=$((MARGIN + VERTICAL_SPACING + row * (IMAGE_HEIGHT + VERTICAL_SPACING)))
            
            # Add to composite command
            composite_cmd="$composite_cmd \"$current_image\" -geometry +${x}+${y} -composite"
            
            ((image_index++))
            ((images_on_page++))
        done
    done
    
    # Execute composite command and force TrueColor output
    eval "$composite_cmd -type TrueColor \"$page_file\""
    
    echo "  Added $images_on_page images to page $page_num"
    ((page_num++))
done

echo ""
echo "====================="
echo "Complete! Created $total_pages page(s) in '$OUTPUT_DIR'"
echo "Ready to print at ${DPI} DPI"
